name: Publish package to NuGet gallery

on:
  release:
    types: [created, edited]

jobs:
  test:
    uses: ./.github/workflows/build-and-test.yml

  deploy:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release ./Deuces.DotNet/Deuces.csproj
      - name: Create the package
        run: dotnet pack --configuration Release ./Deuces.DotNet/Deuces.csproj
      - name: Publish the package to nuget.org
        run: dotnet nuget push ./Deuces.DotNet/bin/Release/*.nupkg --api-key $NUGET_AUTH_TOKEN --source https://api.nuget.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN }}